#!/usr/bin/env python3
"""
add_english.py – inject `en` (English) translations into all world*.json files.
Words not in the dictionary keep en="" so the game can gracefully fall back.
"""
import json, glob, os, re

# ─────────────────────────────────────────────
# COMPREHENSIVE Spanish → English dictionary
# ─────────────────────────────────────────────
EN = {
# ── Acronyms / abbreviations ──
"ADN":"DNA","ONG":"NGO","PIB":"GDP","Vía Láctea":"Milky Way",
# ── A ──
"a":"to","abajo":"below","abdominales":"sit-ups","abeja":"bee",
"abogado":"lawyer","abolir":"to abolish","abono":"fertilizer",
"abrazar":"to hug","abrigo":"coat","abril":"April",
"abuela":"grandmother","abuelo":"grandfather","aburrimiento":"boredom",
"acampar":"to camp","acantilado":"cliff","accidente":"accident",
"acción":"stock","aceite":"oil","acera":"sidewalk","acero":"steel",
"acogida":"reception","acompañar":"to accompany","acostarse":"to lie down",
"actitud":"attitude","actividad":"activity","activismo":"activism",
"acto":"act","actor":"actor","actriz":"actress","actualización":"update",
"acuarela":"watercolor","acuerdo":"agreement","adelantamiento":"overtaking",
"además":"furthermore","adicción":"addiction","adiós":"goodbye",
"administración":"administration","adolescencia":"adolescence",
"aduana":"customs","adulto":"adult","aeropuerto":"airport",
"afeitadora":"razor","afición":"hobby","agenda":"agenda",
"agosto":"August","agradecer":"to thank","agricultor":"farmer",
"agua":"water","agua con gas":"sparkling water","agua potable":"tap water",
"aguacate":"avocado","aguacero":"downpour","aguja":"needle",
"agujero negro":"black hole","ahorrar":"to save","ahorro":"savings",
"ahumar":"to smoke","ahí":"there","aire":"air",
"aire acondicionado":"air conditioning","ajedrez":"chess","ajo":"garlic",
"al lado":"next to","alarma":"alarm","alarma de incendio":"fire alarm",
"albahaca":"basil","alcachofa":"artichoke","alcalde":"mayor",
"alcantarilla":"drain","alcantarillado":"sewage","aldea":"village",
"alegre":"cheerful","alegría":"joy","alergia":"allergy",
"alergia alimentaria":"food allergy","alerta":"alert",
"alfabetización":"literacy","alfombra":"carpet","algoritmo":"algorithm",
"aliado":"ally","alianza":"alliance","alivio":"relief","allí":"over there",
"alma":"soul","almacenamiento":"storage","almacén":"warehouse",
"almeja":"clam","almendra":"almond","almohada":"pillow",
"almuerzo":"lunch","alojamiento":"accommodation","alquiler":"rent",
"altavoz":"speaker","alto":"tall","aluminio":"aluminum","alumno":"student",
"amable":"kind","amanecer":"dawn","amargo":"bitter","amarillo":"yellow",
"ambición":"ambition","ambiente laboral":"work environment",
"ambulancia":"ambulance","amigo":"friend","amor":"love",
"amplificador":"amplifier","analfabetismo":"illiteracy",
"analista":"analyst","analizar":"to analyze","ancho":"wide",
"anchoa":"anchovy","anciano":"elderly person","andamio":"scaffold",
"andén":"platform","anillo":"ring","ansiedad":"anxiety",
"anteayer":"the day before yesterday","antibiótico":"antibiotic",
"antiguo":"ancient","antigüedad":"antique","análisis":"analysis",
"apagar la luz":"to turn off the light","aparcamiento":"parking lot",
"apelación":"appeal","apetito":"appetite","apio":"celery",
"aplauso":"applause","aplicación":"app","aprender":"to learn",
"aprendizaje automático":"machine learning",
"aprendizaje profundo":"deep learning","aprobado":"pass",
"aquello":"that","aquí":"here","arado":"plow","arancel":"tariff",
"araña":"spider","arbusto":"bush","archivo":"file","arcilla":"clay",
"arcoíris":"rainbow","ardilla":"squirrel","arena":"sand","arma":"weapon",
"armario":"wardrobe","aromático":"aromatic","arqueología":"archaeology",
"arquitecto":"architect","arreglar":"to fix","arriba":"above",
"arroyo":"stream","arroz":"rice","arruga":"wrinkle","arte":"art",
"artista":"artist","artículo":"article","arándano":"blueberry",
"asar":"to roast","ascenso":"promotion","ascensor":"elevator",
"asesinato":"murder","asesor legal":"legal advisor","asiento":"seat",
"asilo":"asylum","asistente virtual":"virtual assistant",
"aspiradora":"vacuum cleaner","asteroide":"asteroid",
"astronauta":"astronaut","atajo":"shortcut","atardecer":"sunset",
"atasco":"traffic jam","ateo":"atheist","aterrizaje":"landing",
"atletismo":"athletics","atún":"tuna","aula":"classroom",
"aunque":"although","aurora":"aurora","autobús":"bus",
"automatización":"automation","automatizado":"automated",
"automático":"automatic","autopista":"highway","autor":"author",
"autoridad":"authority","autorretrato":"selfie","avalancha":"avalanche",
"avellana":"hazelnut","avena":"oats","avenida":"avenue",
"aventura":"adventure","avión":"airplane","ayer":"yesterday",
"ayuda humanitaria":"humanitarian aid","ayudar":"to help",
"ayuntamiento":"city hall","azafata":"flight attendant","azul":"blue",
"azúcar":"sugar",
# ── B ──
"bacalao":"cod","bacteria":"bacteria","bahía":"bay","bailar":"to dance",
"bailarín":"dancer","bajo":"short","balcón":"balcony","ballena":"whale",
"ballet":"ballet","baloncesto":"basketball","balonmano":"handball",
"bambú":"bamboo","banco":"bank","banco del parque":"park bench",
"banco público":"bench","bandeja":"tray","banquete":"banquet",
"baraja":"deck of cards","barato":"cheap","barba":"beard",
"barbilla":"chin","barco":"ship","barman":"bartender","barra":"bar",
"barrer":"to sweep","barrio":"neighborhood","base":"base",
"base de datos":"database","basura":"trash","batalla":"battle",
"batata":"sweet potato","batería":"drums","batido":"milkshake",
"batir":"to whisk","bañera":"bathtub","baño":"bathroom","beber":"to drink",
"bebida":"drink","bebé":"baby","beca":"scholarship","berenjena":"eggplant",
"bibliografía":"bibliography","biblioteca":"library","bicicleta":"bicycle",
"bien":"well","bienestar":"well-being","bienvenido":"welcome",
"billete":"bill","biodiversidad":"biodiversity","biología":"biology",
"bistec":"steak","biólogo":"biologist","blanco":"white","blando":"soft",
"blog":"blog","bluetooth":"Bluetooth","blusa":"blouse","boca":"mouth",
"bocacalle":"side street","boda":"wedding","boicot":"boycott",
"bolsa":"bag","bolso":"purse","bolígrafo":"pen","bombero":"firefighter",
"bomberos":"fire station","bombilla":"light bulb",
"bombilla eléctrica":"electric bulb","bombón":"bonbon","bonita":"pretty",
"bonito":"pretty","bordado":"embroidery","bordillo":"curb",
"borracho":"drunk","bosque":"forest","botas":"boots","boxeo":"boxing",
"brazo":"arm","brecha":"gap","brillar":"to shine","brindis":"toast",
"brisa":"breeze","brocha":"brush","brotar":"to sprout",
"brócoli":"broccoli","brújula":"compass","buceo":"scuba diving",
"budismo":"Buddhism","buen provecho":"enjoy your meal",
"buen viaje":"bon voyage","buena suerte":"good luck",
"buenas noches":"good night","buenas tardes":"good afternoon",
"bueno":"good","buenos días":"good morning","bufanda":"scarf",
"buffet":"buffet","bulevar":"boulevard","burrito":"burrito",
"burro":"donkey","butaca":"seat","buzón":"mailbox",
"bádminton":"badminton","béisbol":"baseball","búho":"owl",
# ── C ──
"caballo":"horse","cabello":"hair","cabeza":"head","cable":"cable",
"cabra":"goat","cacahuete":"peanut","cactus":"cactus",
"cadena de suministro":"supply chain","cadera":"hip",
"cafetera":"coffee maker","cafetería":"cafeteria","café":"coffee",
"cajero automático":"ATM","cajón":"drawer","calabaza":"pumpkin",
"calamar":"squid","calcetines":"socks","calcular":"to calculate",
"calefacción":"heating","calendario":"calendar",
"calentamiento":"warm-up","calentamiento global":"global warming",
"calentar":"to heat","calidad":"quality","caliente":"hot",
"calificación":"grade","calle":"street","callejón":"alley",
"calor":"heat","calvo":"bald","cama":"bed","camarero":"waiter",
"camarón":"shrimp","cambio":"change","cambio climático":"climate change",
"cambio social":"social change","caminata":"hike","camino":"path",
"camisa":"shirt","camiseta":"t-shirt","camión":"truck",
"campamento":"campground","campaña":"campaign","campo":"field",
"campus":"campus","canal":"channel","cancha":"court","canción":"song",
"candidato":"candidate","canela":"cinnamon","cangrejo":"crab",
"cansado":"tired","cantante":"singer","cantar":"to sing",
"cantimplora":"canteen","capa de ozono":"ozone layer",
"capacitar":"to train","capital":"capital","captura de pantalla":"screenshot",
"capítulo":"chapter","cara":"face","caramelo":"caramel",
"carbono":"carbon","carbón":"coal","cargador":"charger","cariño":"affection",
"carnaval":"carnival","carne":"meat","carne molida":"ground meat",
"caro":"expensive","carpeta":"folder","carpintero":"carpenter",
"carpintería":"carpentry","carrera":"career","carretera":"road",
"carril":"lane","carta":"menu","cartera":"wallet","cartero":"mailman",
"carácter":"character","casa":"house","cascada":"waterfall",
"castaña":"chestnut","castillo":"castle","castillo de arena":"sand castle",
"catedral":"cathedral","catedrático":"professor","catorce":"fourteen",
"cañón":"canyon","cebada":"barley","cebolla":"onion","cebra":"zebra",
"cedro":"cedar","ceja":"eyebrow","celebración":"celebration",
"celeste":"sky blue","celoso":"jealous","celular":"cell phone",
"cementerio":"cemetery","cemento":"cement","cena":"dinner",
"cenar":"to have dinner","censo":"census","censura":"censorship",
"centeno":"rye","centro":"center","centro comercial":"shopping mall",
"cepillarse los dientes":"to brush teeth","cepillo de dientes":"toothbrush",
"cerca":"near","cerca de":"near to","cerdo":"pork","cereal":"cereal",
"cerebro":"brain","cereza":"cherry","cerrar la puerta":"to close the door",
"certificado":"certificate","cerveza":"beer","cerámica":"ceramics",
"ceviche":"ceviche","chaleco salvavidas":"life jacket",
"champiñón":"mushroom","champán":"champagne","champú":"shampoo",
"chaqueta":"jacket","chatbot":"chatbot","chef":"chef","cheque":"check",
"chip":"chip","chocolate":"chocolate","chocolate caliente":"hot chocolate",
"chorizo":"chorizo","chuleta":"chop","churro":"churro",
"cicatriz":"scar","ciclismo":"cycling","ciclón":"cyclone",
"cielo":"sky","cien":"hundred","ciencia":"science","científico":"scientist",
"ciervo":"deer","cigarra":"cicada","cilantro":"cilantro",
"cimiento":"foundation","cinco":"five","cincuenta":"fifty",
"cine":"cinema","cinta adhesiva":"tape","cinta de correr":"treadmill",
"cinturón":"belt","cinturón de seguridad":"seatbelt",
"circuito":"circuit","circulación":"circulation","ciruela":"plum",
"cirugía":"surgery","cirujano":"surgeon","ciudad":"city",
"ciudadano":"citizen","ciudadanía":"citizenship","civilización":"civilization",
"clara":"egg white","clase":"class","clase social":"social class",
"clasificación":"classification","clasificar":"to classify","clavo":"nail",
"cliente":"customer","clima":"climate","closet":"closet",
"clásica":"classical","coalición":"coalition","cobarde":"coward",
"cobre":"copper","cocción al vapor":"steaming","coche":"car",
"cocina":"kitchen","cocinar":"to cook","cocinero":"cook","coco":"coconut",
"codo":"elbow","cohete":"rocket","col":"cabbage","colaborar":"to collaborate",
"colador":"strainer","colchón":"mattress","colección":"collection",
"colgar":"to hang up","coliflor":"cauliflower","colina":"hill",
"colonia":"colony","columna":"column","columpio":"swing",
"combustible":"fuel","comedia":"comedy","comedor":"dining room",
"comentario":"comment","comer":"to eat","comercio":"trade",
"comercio electrónico":"e-commerce","cometa":"kite","compañero":"colleague",
"compartir":"to share","competencia":"competition",
"comportamiento":"behavior","compositor":"composer","comprar":"to buy",
"comprobar":"to check","compromiso":"commitment","compuesto":"compound",
"computadora":"computer","comunicación":"communication",
"comunidad":"community","con":"with","con mucho gusto":"with pleasure",
"con permiso":"excuse me","conciencia social":"social awareness",
"concierto":"concert","conclusión":"conclusion","condena":"sentence",
"conducción autónoma":"autonomous driving","conductor":"driver",
"conectar":"to connect","conejo":"rabbit","conexión":"connection",
"conferencia":"conference","confesar":"to confess","confeti":"confetti",
"confianza":"trust","confiar":"to trust","conflicto":"conflict",
"congelar":"to freeze","congestión":"congestion","conocido":"acquaintance",
"conquista":"conquest","conserjería":"concierge","conservación":"conservation",
"conservador":"conservative","constelación":"constellation",
"constitución":"constitution","construcción":"construction",
"construir":"to build","consulta":"consultation","consumo":"consumption",
"contador":"accountant","contaminación":"pollution","contar":"to tell",
"contenido":"content","contestar":"to answer","continente":"continent",
"contraseña":"password","contratar":"to hire","contrato":"contract",
"contribuir":"to contribute","control":"control",
"control de calidad":"quality control","convencer":"to convince",
"convivencia":"coexistence","cooperación":"cooperation",
"cooperar":"to cooperate","coordenadas":"coordinates","copa":"wine glass",
"coraje":"courage","coral":"coral","corazón":"heart","corbata":"tie",
"cordero":"lamb","coreografía":"choreography","coro":"choir",
"corrección":"correction","correo":"mail","correo electrónico":"email",
"correos":"post office","correr":"to run","corriente":"current",
"corrupción":"corruption","corrupción política":"political corruption",
"cortar":"to cut","corteza":"bark","cortina":"curtain","corto":"short",
"cosecha":"harvest","cosechar":"to harvest","costa":"coast",
"costilla":"rib","costumbre":"custom","costura":"sewing",
"creatividad":"creativity","creativo":"creative","crecer":"to grow",
"crecimiento":"growth","creer":"to believe","crema":"cream",
"creo que no":"I don't think so","creo que sí":"I think so",
"crimen":"crime","crisis":"crisis","cristal":"crystal",
"cristianismo":"Christianity","cruce":"intersection","crudo":"raw",
"cruel":"cruel","crujiente":"crunchy","crédito":"credit",
"cuaderno":"notebook","cuadrado":"square","cuajada":"curd",
"cualificación":"qualification","cuando":"when","cuarenta":"forty",
"cuarto":"fourth","cuatro":"four","cuchara":"spoon","cucharón":"ladle",
"cuchillo":"knife","cuello":"neck","cuenta":"bill",
"cuento":"fairy tale","cuerpo":"body","cuervo":"crow","cueva":"cave",
"culpa":"guilt","culpable":"guilty","cultura":"culture","cumbre":"summit",
"cumpleaños":"birthday","cuota de mercado":"market share",
"currículum":"resume","cuídate":"take care","cálculo":"calculus",
"cámara":"camera","cámara web":"webcam","cárcel":"jail","célula":"cell",
"césped":"lawn","cóctel":"cocktail","código":"code",
"código postal":"zip code","cómic":"comic",
# ── D ──
"dado":"die","danza":"dance","dar":"to give","dato":"data","datos":"data",
"de":"of","de nada":"you're welcome","debate":"debate","deberes":"homework",
"decepción":"disappointment","decir":"to say","decoración":"decoration",
"decreto":"decree","dedo":"finger","defender":"to defend",
"deforestación":"deforestation","delantal":"apron","delante de":"in front of",
"delfín":"dolphin","delgado":"slim","delincuencia":"crime",
"delito":"crime","demanda":"lawsuit","democracia":"democracy",
"demostrar":"to demonstrate","dentista":"dentist","dentro de":"inside",
"denunciar":"to report","departamento":"department","dependiente":"clerk",
"depósito":"deposit","derecha":"right","derecho":"right",
"derechos humanos":"human rights","derretir":"to melt","derrota":"defeat",
"desarrollar":"to develop","desarrollo":"development",
"desarrollo sostenible":"sustainable development",
"desayunar":"to have breakfast","desayuno":"breakfast",
"desayuno incluido":"breakfast included","descafeinado":"decaffeinated",
"descansar":"to rest","descanso":"rest","descargar":"to download",
"desconfiado":"suspicious","descubrimiento":"discovery",
"descuento":"discount","desempleo":"unemployment",
"desesperación":"despair","desfile":"parade","desierto":"desert",
"desigualdad":"inequality","deslizamiento":"landslide",
"desobediencia civil":"civil disobedience","desodorante":"deodorant",
"despedir":"to fire","despedirse":"to say goodbye","despegue":"takeoff",
"despensa":"pantry","despertar":"to wake up","despido":"dismissal",
"destinatario":"recipient","destino":"destination",
"destornillador":"screwdriver","desvío":"detour","detective":"detective",
"detergente":"detergent","detrás":"behind","detrás de":"behind",
"deuda":"debt","diagnóstico":"diagnosis","diamante":"diamond",
"diapositiva":"slide","dibujar":"to draw","dibujo":"drawing",
"diciembre":"December","dictadura":"dictatorship","diecinueve":"nineteen",
"dieciocho":"eighteen","diecisiete":"seventeen","dieciséis":"sixteen",
"diente":"tooth","dieta":"diet","diez":"ten","difícil":"difficult",
"digestión":"digestion","digital":"digital","dignidad":"dignity",
"dinastía":"dynasty","dinero":"money","diplomacia":"diplomacy",
"dirección":"address","dirección postal":"postal address",
"director":"director","dirigir":"to manage","disciplina":"discipline",
"disco duro":"hard drive","discriminación":"discrimination",
"disculparse":"to apologize","disculpe":"excuse me","discurso":"speech",
"discutir":"to discuss","diseñador":"designer","diseño":"design",
"disfraz":"costume","disfrutar":"to enjoy","disparo":"shot",
"dispositivo":"device","distancia":"distance","distrito":"district",
"diversidad":"diversity","diversión":"fun","división":"division",
"diáspora":"diaspora","doble":"double","doce":"twelve",
"doctorado":"PhD","documental":"documentary","dolor":"pain",
"domingo":"Sunday","donut":"donut","dorado":"golden","dormir":"to sleep",
"dormitorio":"bedroom","dos":"two","droga":"drug","ducha":"shower",
"ducharse":"to shower","dulce":"sweet","durazno":"peach","duro":"hard",
"débil":"weak","décimo":"tenth","día laborable":"weekday",
# ── E ──
"eclipse":"eclipse","ecologismo":"environmentalism","ecológico":"ecological",
"economía":"economy","ecosistema":"ecosystem","ecuación":"equation",
"edad":"age","edificio":"building","editor":"editor","editorial":"editorial",
"educación":"education","educación física":"physical education",
"efectivo":"cash","efecto invernadero":"greenhouse effect",
"eficiencia":"efficiency","egoísta":"selfish","ejercicio":"exercise",
"ejército":"army","elección":"election","electricidad":"electricity",
"electricista":"electrician","electrónica":"electronics",
"electrónico":"electronic","elefante":"elephant","elegir":"to elect",
"elemento":"element","ella":"she","ellos":"they","embajada":"embassy",
"embajador":"ambassador","embarazo":"pregnancy","embarque":"boarding",
"emergencia":"emergency","emigración":"emigration","emisión":"emission",
"emisora":"radio station","emoción":"emotion","emoji":"emoji",
"empadronamiento":"census registration","empanada":"empanada",
"empleado":"employee","empleo":"employment","empresa":"company",
"empresario":"businessman","en":"in","en directo":"live",
"enchilada":"enchilada","enchufe":"outlet","encontrar":"to find",
"encuadre":"framing","encuesta":"survey","enemigo":"enemy",
"energía":"energy","energía eólica":"wind energy",
"energía renovable":"renewable energy","energía solar":"solar energy",
"enero":"January","enfermedad":"illness","enfermero":"nurse",
"enfoque":"focus","enfrente":"across from","enfriar":"to cool",
"engranaje":"gear","enojo":"anger","ensamblaje":"assembly",
"ensayo":"rehearsal","enseñanza":"teaching","enseñar":"to teach",
"entonces":"then","entrada":"entrance","entre":"between",
"entrega":"delivery","entrenador":"trainer","entrenamiento":"training",
"entretenimiento":"entertainment","entrevista":"interview",
"entusiasmo":"enthusiasm","enviar":"to send","envidia":"envy",
"epicentro":"epicenter","epidemia":"epidemic","episodio":"episode",
"equilibrio":"balance","equipaje":"luggage","equipo":"team",
"error":"error","erupción":"eruption","escala":"layover",
"escalada":"rock climbing","escalera":"stairs","escarabajo":"beetle",
"escarcha":"frost","escaño":"seat","escena":"scene","escenario":"stage",
"esclavitud":"slavery","escoba":"broom","escribir":"to write",
"escritor":"writer","escritorio":"desk","escuchar":"to listen",
"escuela":"school","escultor":"sculptor","escultura":"sculpture",
"escándalo":"scandal","esgrima":"fencing","esnórquel":"snorkeling",
"eso":"that","espacio":"space","espalda":"back",
"especial del día":"daily special","especie":"species","espejo":"mirror",
"esperanza":"hope","espinaca":"spinach","esposa":"wife","esposo":"husband",
"espárrago":"asparagus","espátula":"spatula","esqueleto":"skeleton",
"esquina":"corner","esquí":"skiing","esta semana":"this week",
"estacionamiento":"parking","estación":"station","estadio":"stadium",
"estado":"state","estadística":"statistics","estanque":"pond",
"estante":"shelf","estar":"to be","estatua":"statue","este":"east",
"estiramiento":"stretching","esto":"this","estoy cansado":"I'm tired",
"estrategia":"strategy","estrecho":"narrow","estrella":"star",
"estrella de mar":"starfish","estreno":"premiere","estructura":"structure",
"estrés":"stress","estrés laboral":"work stress","estudiante":"student",
"estudiar":"to study","estudio":"study","estufa":"stove",
"está bien":"it's okay","estómago":"stomach","etnia":"ethnicity",
"evacuación":"evacuation","evidencia":"evidence","evolución":"evolution",
"examen":"exam","excursión":"excursion","experiencia":"experience",
"experimentar":"to experiment","experimento":"experiment",
"explicar":"to explain","exploración":"exploration","explotación":"exploitation",
"exportación":"export","exposición":"exhibition",
"exposición fotográfica":"photographic exposure","extinción":"extinction",
"extintor":"fire extinguisher","extranjero":"foreigner","extraño":"stranger",
# ── F ──
"fabricación":"manufacturing","factura":"invoice","facturación":"check-in",
"facultad":"faculty","falda":"skirt","familia":"family","farmacia":"pharmacy",
"farmacéutico":"pharmacist","farola":"streetlight","fatiga":"fatigue",
"fe":"faith","febrero":"February","felicidad":"happiness",
"felicidades":"congratulations","felicitar":"to congratulate",
"feminismo":"feminism","feo":"ugly","fertilizante":"fertilizer",
"festival":"festival","fibra":"fiber","ficha":"game piece",
"fideos":"noodles","fiebre":"fever","fiesta":"party","filete":"fillet",
"filosofía":"philosophy","filtro":"filter","fin de semana":"weekend",
"firmar":"to sign","fiscal":"prosecutor","flan":"flan","flash":"flash",
"flauta":"flute","flexión":"push-up","flor":"flower","florecer":"to bloom",
"foca":"seal","fogata":"bonfire","formación":"training","fotocopiadora":"copier",
"fotografiar":"to photograph","fotografía":"photography",
"fotosíntesis":"photosynthesis","fotógrafo":"photographer",
"fracción":"fraction","fractura":"fracture","frambuesa":"raspberry",
"fraude":"fraud","fregar":"to scrub","freno":"brake","frente":"forehead",
"fresa":"strawberry","fresco":"fresh","freír":"to fry",
"fricción":"friction","frijol":"bean","frontera":"border",
"frustración":"frustration","fruta":"fruit","frío":"cold","fuego":"fire",
"fuegos artificiales":"fireworks","fuente":"fountain","fuerte":"strong",
"fuerza":"strength","funcionario":"official","funda":"case",
"furgoneta":"van","fábrica":"factory","fácil":"easy","física":"physics",
"físico":"physicist","fórmula":"formula","fósil":"fossil","fútbol":"soccer",
# ── G ──
"gafas":"glasses","gafas de sol":"sunglasses","galaxia":"galaxy",
"galería":"gallery","galleta":"cookie","gallina":"hen","ganado":"livestock",
"ganador":"winner","ganancia":"profit","garaje":"garage",
"garbanzo":"chickpea","gas":"gas","gasolina":"gasoline",
"gasolinera":"gas station","gastar":"to spend","gato":"cat",
"gazpacho":"gazpacho","gelatina":"gelatin","gema":"gem","gen":"gene",
"generación":"generation","generador":"generator","generoso":"generous",
"gentrificación":"gentrification","geografía":"geography",
"geometría":"geometry","gimnasia":"gymnastics","gimnasio":"gym",
"gira":"tour","girasol":"sunflower","glaciar":"glacier",
"globalización":"globalization","globo":"balloon","glorieta":"roundabout",
"gobernar":"to govern","gobierno":"government","golf":"golf",
"golondrina":"swallow","goma de borrar":"eraser","gordo":"fat",
"gorra":"cap","gorrión":"sparrow","gracias":"thank you",
"graduación":"graduation","granada":"pomegranate","grande":"big",
"granizo":"hail","granja":"farm","grapadora":"stapler","grasoso":"greasy",
"gratitud":"gratitude","gravedad":"gravity","gravedad cero":"zero gravity",
"grillo":"cricket","gripe":"flu","gris":"gray","gritar":"to shout",
"grosero":"rude","grupo":"group","gráfico":"graph","grúa":"crane",
"guacamole":"guacamole","guantes":"gloves","guapo":"handsome",
"guardería":"daycare","guardia":"guard","guerra":"war","guion":"script",
"guisante":"pea","guisar":"to stew","guitarra":"guitar","gusto":"taste",
"guía":"guide","guía turístico":"tour guide","género":"gender",
# ── H ──
"habilidad":"skill","habitación":"room","habitante":"inhabitant",
"hablar":"to speak","hacer":"to do","hacia":"towards",
"halterofilia":"weightlifting","hamaca":"hammock","hambre":"hunger",
"hambruna":"famine","harina":"flour","hashtag":"hashtag",
"hasta luego":"see you later","hasta mañana":"see you tomorrow",
"helada":"frost","helado":"ice cream","helecho":"fern",
"helicóptero":"helicopter","herencia":"genetics","herida":"wound",
"hermana":"sister","hermano":"brother","herramienta":"tool",
"hervir":"to boil","hidrógeno":"hydrogen","hielo":"ice","hierba":"grass",
"hierro":"iron","higiene":"hygiene","higo":"fig","hija":"daughter",
"hijo":"son","hilo":"thread","hip hop":"hip hop",
"hipopótamo":"hippopotamus","hipoteca":"mortgage","hipótesis":"hypothesis",
"historia":"history","hogar":"home","hoja":"leaf","hola":"hello",
"hombre":"man","hombro":"shoulder","honesto":"honest","honradez":"honesty",
"horario":"schedule","horizonte":"horizon","hormiga":"ant","hornear":"to bake",
"horno":"oven","hospital":"hospital","hostal":"hostel","hotel":"hotel",
"hoy":"today","huelga":"strike","huella de carbono":"carbon footprint",
"huerto":"orchard","hueso":"bone","huevo":"egg","humedad":"humidity",
"humilde":"humble","huracán":"hurricane","huésped":"guest",
"hábitat":"habitat","hámster":"hamster","hígado":"liver","húmedo":"humid",
# ── I ──
"ida":"one way","ida y vuelta":"round trip","identidad":"identity",
"ideología":"ideology","idioma":"language","iglesia":"church",
"igualdad":"equality","igualmente":"likewise","ilusión":"excitement",
"impaciente":"impatient","impar":"odd","imperio":"empire",
"importación":"import","imprenta":"printing press","impresora":"printer",
"impuesto":"tax","incendio":"fire","incendio forestal":"forest fire",
"independencia":"independence","indicación":"indication",
"indigencia":"homelessness","industria":"industry","infancia":"childhood",
"infección":"infection","inflación":"inflation","inflamación":"inflammation",
"influencer":"influencer","informe":"report","informática":"computer science",
"infusión":"herbal tea","ingeniero":"engineer","ingeniería":"engineering",
"inglés":"English","ingrediente":"ingredient","inmigración":"immigration",
"inmobiliaria":"real estate","inmunidad":"immunity","innovación":"innovation",
"inocente":"innocent","inodoro":"toilet","inquilino":"tenant",
"insomnio":"insomnia","insípido":"bland","integración":"integration",
"inteligencia artificial":"artificial intelligence","inteligente":"intelligent",
"intermitente":"turn signal","internet":"internet","interruptor":"switch",
"intervención":"intervention","interés":"interest","inundación":"flood",
"invención":"invention","inventar":"to invent","inventor":"inventor",
"invernadero":"greenhouse","inversión":"investment",
"investigación":"research","investigación académica":"academic research",
"investigador":"researcher","investigar":"to research","invierno":"winter",
"invitación":"invitation","invitado":"guest","invitar":"to invite",
"inyección":"injection","ir":"to go","ir al trabajo":"to go to work",
"irresponsable":"irresponsible","isla":"island","islam":"Islam",
"itinerario":"itinerary","izquierda":"left",
# ── J ──
"jabón":"soap","jamón":"ham","jardín":"garden","jarra":"pitcher",
"jazmín":"jasmine","jazz":"jazz","jefe":"boss","jengibre":"ginger",
"jirafa":"giraffe","joven":"young","joyería":"jewelry",
"jubilación":"retirement","judo":"judo","judía verde":"green bean",
"juego":"game","jueves":"Thursday","juez":"judge","jugador":"player",
"jugar":"to play","jugo":"juice","jugoso":"juicy","juicio":"trial",
"julio":"July","junio":"June","jurado":"jury","justicia":"justice",
"juventud":"youth","juzgar":"to judge",
# ── K ──
"kayak":"kayak","kilómetro":"kilometer","kiwi":"kiwi",
# ── L ──
"labio":"lip","laboratorio":"laboratory","ladrillo":"brick","ladrón":"thief",
"lago":"lake","lago artificial":"artificial lake","langosta":"lobster",
"lanzamiento":"launch","largo":"long","lavadero":"laundry room",
"lavadora":"washing machine","lavandería":"laundromat",
"lavar la ropa":"to do laundry","lavar los platos":"to wash dishes",
"lavarse la cara":"to wash one's face","lavavajillas":"dishwasher",
"leal":"loyal","leche":"milk","leche de almendra":"almond milk",
"lechuga":"lettuce","lector":"reader","leer":"to read",
"leer un libro":"to read a book","legislar":"to legislate","lejos":"far",
"lejos de":"far from","lengua":"tongue","lenteja":"lentil","lento":"slow",
"leopardo":"leopard","letra":"lyrics","levantarse":"to get up","ley":"law",
"leña":"firewood","león":"lion","liberal":"liberal","libertad":"freedom",
"librería":"bookstore","libro":"book","libro de texto":"textbook",
"libélula":"dragonfly","licenciatura":"bachelor's degree","licor":"liqueur",
"licuadora":"blender","liderazgo":"leadership","lienzo":"canvas",
"ligero":"light","limonada":"lemonade","limpiador":"cleaner",
"limpiar":"to clean","limpio":"clean","limón":"lemon","linterna":"flashlight",
"literatura":"literature","llamada":"phone call","llamar":"to call",
"llanura":"plain","llave":"key","llave inglesa":"wrench","llegada":"arrival",
"lleno":"full","llevar":"to carry","llover":"to rain","lluvia":"rain",
"lo siento":"I'm sorry","lobo":"wolf","loro":"parrot","loto":"lotus",
"lucha":"wrestling","luna":"moon","lunes":"Monday","luz":"light",
"lácteo":"dairy","lámpara":"lamp","lápiz":"pencil","láser":"laser",
"límite de velocidad":"speed limit","líquido":"liquid",
# ── M ──
"madre":"mother","madurez":"maturity","maduro":"ripe","maestro":"teacher",
"maestría":"master's degree","magnetismo":"magnetism","magnitud":"magnitude",
"mal":"bad","maleta":"suitcase","malo":"bad","manantial":"spring",
"mandarina":"tangerine","mandato":"mandate","mando a distancia":"remote control",
"mango":"mango","manifestación":"rally","mano":"hand","manta":"blanket",
"mantel":"tablecloth","mantequilla":"butter","manualidad":"craft",
"manzana":"apple","mapa":"map","maquillaje":"makeup",
"maquillarse":"to put on makeup","mar":"sea","maratón":"marathon",
"marca":"brand","marcapáginas":"bookmark","marcar":"to dial",
"marea":"tide","maremoto":"tsunami","mareo":"dizziness",
"margen de beneficio":"profit margin","marinar":"to marinate",
"mariposa":"butterfly","marisco":"seafood","marrón":"brown",
"martes":"Tuesday","martillo":"hammer","marzo":"March","masa":"dough",
"masticar":"to chew","matemáticas":"mathematics","matemático":"mathematician",
"materia prima":"raw material","material":"material","matrícula":"tuition",
"mayo":"May","mayoría":"majority","mazapán":"marzipan","maíz":"corn",
"mañana":"tomorrow","me gusta":"I like it","me llamo":"my name is",
"mecanismo":"mechanism","mecánico":"mechanic","medianoche":"midnight",
"medicamento":"medication","medicina":"medicine","medición":"measurement",
"medieval":"medieval","medio":"half","medio ambiente":"environment",
"medio de comunicación":"media","mediodía":"noon","medir":"to measure",
"medusa":"jellyfish","mejilla":"cheek","mejillón":"mussel",
"melocotón":"peach","melodía":"melody","melón":"melon","memoria":"memory",
"mensaje":"message","mentir":"to lie","mentiroso":"liar","menú":"menu",
"mercado":"market","merienda":"snack","mermelada":"jam","mesa":"table",
"meseta":"plateau","metal":"metal","meteorito":"meteorite","metro":"subway",
"metrópoli":"metropolis","mezclar":"to mix","mi":"my",
"microondas":"microwave","microscopio":"microscope","micrófono":"microphone",
"miedo":"fear","miel":"honey","mientras":"while","migrar":"to migrate",
"mil":"thousand","milagro":"miracle","mineral":"mineral",
"ministro":"minister","minoría":"minority","mirador":"viewpoint",
"miércoles":"Wednesday","mochila":"backpack","modelo":"model",
"moderno":"modern","modestia":"modesty","molde":"mold",
"molécula":"molecule","monarquía":"monarchy","moneda":"coin",
"monitor":"monitor","mono":"monkey","monopolio":"monopoly",
"montaña":"mountain","monumento":"monument","monzón":"monsoon",
"mora":"blackberry","morado":"purple","moreno":"dark-haired",
"morir":"to die","mosquito":"mosquito","mostaza":"mustard",
"motivación":"motivation","motocicleta":"motorcycle","motor":"engine",
"movimiento":"movement","movimiento social":"social movement","mucho":"a lot",
"mucho gusto":"nice to meet you","mudanza":"moving","muerte":"death",
"muestra":"sample","mujer":"woman","multa":"fine",
"multiculturalismo":"multiculturalism","multiplicación":"multiplication",
"multitud":"crowd","murciélago":"bat","muro":"wall","museo":"museum",
"musgo":"moss","musical":"musical","muñeca":"wrist",
"máquina":"machine","mármol":"marble","más o menos":"more or less",
"máscara":"mask","médico":"doctor","método":"method","músculo":"muscle",
"música":"music","músico":"musician",
# ── N ──
"nacer":"to be born","nachos":"nachos","nacimiento":"birth",
"nacionalidad":"nationality","nada":"nothing","nadar":"to swim",
"nanotecnología":"nanotechnology","naranja":"orange","nariz":"nose",
"nata":"cream","natación":"swimming","natilla":"custard","naturaleza":"nature",
"navaja":"pocket knife","nave espacial":"spaceship","navegador":"navigator",
"neblina":"mist","nebulosa":"nebula","negar":"to deny",
"negociación":"negotiation","negociar":"to negotiate","negocio":"business",
"negro":"black","nervio":"nerve","neumático":"tire","neutralidad":"neutrality",
"nevada":"snowfall","nevar":"to snow","nevera":"refrigerator","ni":"neither",
"niebla":"fog","nieve":"snow","nivel":"level","niña":"girl","niñez":"childhood",
"niño":"boy","no":"no","no entiendo":"I don't understand",
"no importa":"it doesn't matter","no me gusta":"I don't like it",
"no sé":"I don't know","noche":"night","nombre":"name","norma":"rule",
"norte":"north","nos vemos":"see you","nosotros":"we","nostalgia":"nostalgia",
"nota":"grade","notario":"notary","noticia":"news","noticias":"news",
"notificación":"notification","novela":"novel","noveno":"ninth",
"noventa":"ninety","novia":"girlfriend","noviembre":"November",
"novio":"boyfriend","nube":"cloud","nuclear":"nuclear","nueve":"nine",
"nuevo":"new","nuez":"walnut","nutrición":"nutrition","nutriente":"nutrient",
"náusea":"nausea","número":"number",
# ── O ──
"o":"or","objetivo":"lens","obra de arte":"artwork",
"obra de teatro":"play","obrero":"worker","observación":"observation",
"observar":"to observe","ochenta":"eighty","ocho":"eight","ocio":"leisure",
"octavo":"eighth","octubre":"October","océano":"ocean","odio":"hatred",
"oeste":"west","oferta":"offer","oferta de empleo":"job offer",
"oficina":"office","oficina de correos":"post office",
"oftalmólogo":"ophthalmologist","ojo":"eye","ola":"wave","olfato":"smell",
"olla":"pot","once":"eleven","onda":"wave","opinar":"to give an opinion",
"opinión":"opinion","oposición":"opposition","opresión":"oppression",
"optimista":"optimistic","oración":"prayer","ordenar":"to tidy",
"oreja":"ear","organismo":"organism",
"organización internacional":"international organization",
"organizar":"to organize","orgullo":"pride","orgulloso":"proud",
"origami":"origami","orilla":"riverbank","oro":"gold","orquesta":"orchestra",
"orquídea":"orchid","orégano":"oregano","oscuro":"dark","oso":"bear",
"ostra":"oyster","otoño":"autumn","otra vez":"again","oveja":"sheep",
"oxígeno":"oxygen","oído":"hearing","onda expansiva":"shockwave",
# ── P ──
"paciencia":"patience","paciente":"patient","pacifismo":"pacifism",
"padre":"father","paella":"paella","pagar":"to pay","paisaje":"landscape",
"pajita":"straw","palacio":"palace","paleta":"palette","palillos":"chopsticks",
"paloma":"pigeon","palomitas":"popcorn","pan":"bread","panadería":"bakery",
"pantalla":"screen","pantalón":"pants","pantalón corto":"shorts",
"pantano":"swamp","papa":"potato","papaya":"papaya","papel":"paper",
"papel higiénico":"toilet paper","paquete":"package","par":"even",
"para":"for","para llevar":"to go","parada":"stop","paraguas":"umbrella",
"paramédico":"paramedic","pared":"wall","pareja":"couple",
"parking":"parking","parlamento":"parliament","parque":"park",
"participante":"participant","participar":"to participate","partida":"game",
"partido":"party","pasado mañana":"day after tomorrow",
"pasajero":"passenger","pasaporte":"passport","pasar":"to pass",
"pasatiempo":"pastime","paseo":"promenade","pasillo":"hallway",
"paso de peatones":"crosswalk","pasta":"pasta",
"pasta de dientes":"toothpaste","pastel":"cake","pastilla":"pill",
"pastoreo":"livestock grazing","patata":"potato","patente":"patent",
"patinaje":"skating","patinete":"scooter","patio":"yard","pato":"duck",
"patrimonio":"heritage","pavimento":"pavement","pavo":"turkey",
"paz":"peace","pañuelo":"handkerchief","peaje":"toll","peatón":"pedestrian",
"pecado":"sin","pecho":"chest","pechuga":"breast","pediatra":"pediatrician",
"pedir":"to order","pegamento":"glue","peinarse":"to comb hair",
"peine":"comb","pelar":"to peel","peligro":"danger","pelota":"ball",
"peluquero":"hairdresser","peluquería":"hair salon","película":"movie",
"penicilina":"penicillin","pensar":"to think","pensión":"bed and breakfast",
"península":"peninsula","pepino":"cucumber","pequeño":"small","pera":"pear",
"perdedor":"loser","perdonar":"to forgive","perdón":"sorry",
"perejil":"parsley","perezoso":"lazy","perfil":"profile",
"perfume":"perfume","periodista":"journalist","periódico":"newspaper",
"permiso de conducir":"driver's license","pero":"but","perro":"dog",
"perseverancia":"perseverance","persona":"person","pesado":"heavy",
"pesas":"weights","pesca":"fishing","pescado":"fish",
"pesimista":"pessimistic","peso":"weight","pestaña":"eyelash",
"petición":"petition","petróleo":"oil","pez":"fish","piano":"piano",
"picante":"spicy","picar":"to chop","picnic":"picnic","pie":"foot",
"piedra":"stone","piel":"skin","pierna":"leg","pilates":"pilates",
"piloto":"pilot","pimienta":"pepper","pimiento":"pepper",
"pincel":"paintbrush","ping-pong":"ping pong","pino":"pine",
"pintar":"to paint","pintor":"painter","pintura":"painting",
"piscina":"swimming pool","piso":"apartment","pista":"runway",
"pistacho":"pistachio","pizarra":"whiteboard","piña":"pineapple",
"plan de estudios":"curriculum","plan de negocios":"business plan",
"planchar":"to iron","planeta":"planet","planificación urbana":"urban planning",
"planificar":"to plan","plano":"blueprint","plano arquitectónico":"floor plan",
"planta":"floor","plantar":"to plant","plata":"silver","plataforma":"platform",
"plateado":"silver","plato":"plate","plato principal":"main course",
"playa":"beach","plaza":"square","plazo":"deadline",
"plazo de entrega":"delivery deadline","plástico":"plastic","plátano":"banana",
"población":"population","pobreza":"poverty","poco":"a little",
"podcast":"podcast","poder":"power","poesía":"poetry","poeta":"poet",
"polar":"polar","polen":"pollen","policía":"police","pollo":"chicken",
"polo acuático":"water polo","polvorón":"polvoron","política":"politics",
"poner":"to put","ponerse el pijama":"to put on pajamas","pop":"pop",
"por":"by","por favor":"please","porcentaje":"percentage","porción":"portion",
"porque":"because","portada":"cover","portero":"gatekeeper",
"portería":"goal","portátil":"laptop","postre":"dessert","postura":"posture",
"potencia":"power","pradera":"prairie","precio":"price",
"precisión":"precision","predicción":"prediction","pregunta":"question",
"preguntar":"to ask","prejuicio":"prejudice","prensa":"press",
"preparar":"to prepare","presentación":"presentation",
"presentador":"presenter","presentar":"to introduce","presidente":"president",
"presión":"pressure","presupuesto":"budget","prevención":"prevention",
"primavera":"spring","primero":"first","primeros auxilios":"first aid",
"primo":"cousin","prisa":"hurry","prisión":"prison","privacidad":"privacy",
"probar":"to taste","problema social":"social problem",
"procesador":"processor","procesamiento":"processing",
"producción":"production","producir":"to produce",
"productividad":"productivity","producto":"product","profesor":"teacher",
"programa":"program","programador":"programmer","programar":"to program",
"prohibir":"to prohibit","promedio":"average","prometer":"to promise",
"pronóstico":"forecast","propaganda":"propaganda","propiedad":"property",
"propiedad intelectual":"intellectual property","propietario":"owner",
"propina":"tip","propuesta":"proposal","protagonista":"protagonist",
"protector solar":"sunscreen","protesta":"protest","protestar":"to protest",
"proteína":"protein","prototipo":"prototype","proveedor":"supplier",
"proyecto":"project","proyector":"projector","prudencia":"prudence",
"prueba":"evidence","préstamo":"loan","psicólogo":"psychologist",
"publicación":"publication","publicidad":"advertisement","pueblo":"people",
"puente":"bridge","puerta":"door","puerta de embarque":"boarding gate",
"puerto":"port","pues":"well","puesto":"position","pulmón":"lung",
"pulpo":"octopus","punto de referencia":"landmark","puntuación":"score",
"puntualidad":"punctuality","página":"page","página web":"webpage",
"pérdida":"loss","pétalo":"petal","pólvora":"gunpowder","público":"audience",
# ── Q ──
"querer":"to want","quesadilla":"quesadilla","queso":"cheese",
"quince":"fifteen","quinto":"fifth","química":"chemistry","químico":"chemist",
# ── R ──
"racismo":"racism","radar":"radar","rallar":"to grate","rama":"branch",
"rascacielos":"skyscraper","ratón":"mouse","rayo":"lightning",
"raíz":"root","reacción":"reaction","reality show":"reality show",
"recepcionista":"receptionist","recepción":"reception","receta":"recipe",
"recibir":"to receive","recibo":"receipt","reciclaje":"recycling",
"reciclaje urbano":"urban recycling","reclamar":"to demand",
"recomendación":"recommendation","reconocimiento":"recognition",
"recreo":"recess","recuerdo":"souvenir","recuperación":"recovery",
"recurso":"resource","recurso natural":"natural resource",
"recursos humanos":"human resources","red":"network",
"red neuronal":"neural network","red social":"social media",
"redondo":"round","referencia":"reference","referéndum":"referendum",
"reforma":"reform","refresco":"soda","refugiado":"refugee",
"regar":"to water","reggaetón":"reggaeton","registro":"check-in",
"regla":"rule","regular":"to regulate","relaciones internacionales":"international relations",
"relajación":"relaxation","relajarse":"to relax","religión":"religion",
"reloj":"clock","relámpago":"lightning","remitente":"sender",
"remolacha":"beet","renovable":"renewable","renovación":"renovation",
"renuncia":"resignation","renunciar":"to resign","reparar":"to repair",
"repartidor":"delivery person","repaso":"review","reportaje":"report",
"reproducción":"reproduction","república":"republic","requesón":"ricotta",
"res":"beef","resaca":"hangover","rescate":"rescue","reserva":"reservation",
"resfriado":"cold","residuo":"waste","resistencia":"endurance",
"resolución":"resolution","resolver":"to solve","respetar":"to respect",
"respeto":"respect","respiración":"breathing","responder":"to respond",
"responsabilidad":"responsibility","responsabilidad social":"social responsibility",
"responsable":"responsible","respuesta":"answer","resta":"subtraction",
"restaurante":"restaurant","resultado":"result","resumen":"summary",
"retoque":"retouch","retraso":"delay","retrato":"portrait",
"retrovisor":"rearview mirror","reunión":"meeting","revisión":"review",
"revista":"magazine","revolución":"revolution","riego":"irrigation",
"rinoceronte":"rhinoceros","riqueza":"wealth","ritmo":"rhythm",
"roble":"oak","robo":"robbery","robot":"robot","roca":"rock","rock":"rock",
"rocío":"dew","rodilla":"knee","rojo":"red","romero":"rosemary",
"rompecabezas":"puzzle","ron":"rum","ropa interior":"underwear",
"rosa":"pink","rotonda":"roundabout","rotulador":"marker","rubio":"blond",
"rueda":"wheel","rugby":"rugby","ruido":"noise","ruinas":"ruins",
"ruta":"route","rábano":"radish","ráfaga":"gust","rápido":"fast",
"réplica":"aftershock","río":"river",
# ── S ──
"saber":"to know","sabroso":"tasty","sacar la basura":"to take out the trash",
"sacerdote":"priest","saco de dormir":"sleeping bag","sagrado":"sacred",
"sal":"salt","sala":"living room","sala de conferencias":"conference room",
"salado":"salty","salario":"salary","salchicha":"sausage","salida":"exit",
"salida de emergencia":"emergency exit","salida del hotel":"hotel checkout",
"salir":"to go out","salir de casa":"to leave home","salmón":"salmon",
"salsa":"sauce","saltar":"to jump","saltear":"to sauté","salud":"health",
"saludar":"to greet","sanción":"sanction","sandalias":"sandals",
"sandía":"watermelon","sangre":"blood","sangría":"sangria",
"sanidad":"healthcare","sardina":"sardine","sartén":"frying pan",
"satisfacción":"satisfaction","satélite":"satellite","sauce":"willow",
"saxofón":"saxophone","sazonar":"to season","secador":"hair dryer",
"secadora de ropa":"clothes dryer","seco":"dry","secuestro":"kidnapping",
"sed":"thirst","sede central":"headquarters","seguidores":"followers",
"seguir":"to follow","segundo":"second","seguridad":"security",
"seguro":"insurance","seguro médico":"health insurance","seis":"six",
"selfie":"selfie","sello":"stamp","selva":"jungle","semestre":"semester",
"semiconductor":"semiconductor","semilla":"seed","semáforo":"traffic light",
"senderismo":"hiking","sendero":"trail","sensor":"sensor",
"sentadilla":"squat","sentencia":"sentence","sentido":"sense",
"sentir":"to feel","septiembre":"September","sequía":"drought",
"ser":"to be","serie":"TV series","servicio":"service",
"servicio al cliente":"customer service",
"servicio de habitaciones":"room service","servidor":"server",
"servilleta":"napkin","servir":"to serve","sesenta":"sixty",
"setenta":"seventy","sexto":"sixth","señal":"signal",
"si":"if","siembra":"sowing","siempre":"always","sierra":"saw",
"siete":"seven","silla":"chair","simpático":"nice",
"simulación":"simulation","sin":"without","sin embargo":"however",
"sin gluten":"gluten free","sincero":"sincere","sindicato":"union",
"sistema":"system","sitio web":"website","smog":"smog","smoothie":"smoothie",
"soberanía":"sovereignty","soberanía nacional":"national sovereignty",
"sobre":"envelope","sobrepoblación":"overpopulation","sobrino":"nephew",
"sociedad":"society","socio":"partner","software":"software","sofá":"sofa",
"soja":"soy","sol":"sun","soldado":"soldier","soldadura":"welding",
"soledad":"loneliness","solicitud":"application","solidaridad":"solidarity",
"solución":"solution","sombra":"shadow","sombrero":"hat",
"sombrilla":"parasol","sonda":"probe","sonido":"sound","soplar":"to blow",
"sorpresa":"surprise","sospechoso":"suspect","sostenibilidad":"sustainability",
"sostenible":"sustainable","soñar":"to dream","suave":"soft",
"subtítulo":"subtitle","suburbio":"suburb","sucursal":"branch",
"sudadera":"hoodie","sudor":"sweat","suelo":"floor","suero":"serum",
"sueño":"sleep","sufragio":"suffrage","suite":"suite","suma":"addition",
"supermercado":"supermarket","superpotencia":"superpower",
"supervisar":"to supervise","sur":"south","surf":"surfing",
"suscripción":"subscription","suspenso":"fail","susurrar":"to whisper",
"suéter":"sweater","sábado":"Saturday","séptimo":"seventh","sí":"yes",
"síntoma":"symptom","sólido":"solid","sótano":"basement",
# ── T ──
"taberna":"tavern","tabla de cortar":"cutting board",
"tabla de surf":"surfboard","tablero":"board","tacaño":"stingy",
"taco":"taco","tacto":"touch","taekwondo":"taekwondo","taladro":"drill",
"tamales":"tamales","también":"also","tampoco":"neither","tapas":"tapas",
"taquilla":"ticket office","tarea":"task","tarjeta de crédito":"credit card",
"tarjeta de embarque":"boarding pass","tarjeta gráfica":"graphics card",
"tarta":"tart","taxi":"taxi","taxista":"taxi driver","taza":"cup",
"tazón":"bowl","teatro":"theater","techo":"roof","teclado":"keyboard",
"tecnología":"technology","tejido":"knitting","telescopio":"telescope",
"televisión":"television","televisor":"television set",
"teléfono":"telephone","teléfono inteligente":"smartphone","telón":"curtain",
"temperatura":"temperature","templado":"mild","templo":"temple",
"temporada":"season","tender la ropa":"to hang out clothes",
"tenedor":"fork","tener":"to have","tener hambre":"to be hungry",
"tengo hambre":"I'm hungry","tengo sed":"I'm thirsty","tengo sueño":"I'm sleepy",
"tenis":"tennis","teoría":"theory","tequila":"tequila",
"terapeuta":"therapist","tercero":"third","terco":"stubborn",
"terminal":"terminal","ternura":"tenderness","terraza":"terrace",
"terremoto":"earthquake","terror":"terror","terrorismo":"terrorism",
"tesis":"thesis","testigo":"witness","tiburón":"shark",
"tiempo libre":"free time","tienda":"store","tienda de campaña":"tent",
"tierra":"land","tifón":"typhoon","tigre":"tiger","tijeras":"scissors",
"timbre":"doorbell","tiro con arco":"archery","tirolina":"zip line",
"titular":"headline","toalla":"towel","tobillo":"ankle","tobogán":"slide",
"tocar":"to play","tocino":"bacon","todo":"everything",
"tolerancia":"tolerance","tomar el autobús":"to take the bus",
"tomate":"tomato","tomillo":"thyme","tormenta":"storm","tornado":"tornado",
"tornillo":"screw","toro":"bull","torre":"tower",
"tortilla de maíz":"corn tortilla","tortilla española":"Spanish omelette",
"tortuga marina":"sea turtle","tos":"cough","tostada":"toast",
"tostadora":"toaster","trabajador":"hardworking","trabajar":"to work",
"trabajo":"work","trabajo en equipo":"teamwork","tradición":"tradition",
"traductor":"translator","tragar":"to swallow","traje":"suit",
"traje de baño":"swimsuit","tranquilidad":"tranquility",
"transformar":"to transform","transmisión en vivo":"live broadcast",
"transporte público":"public transport",
"transporte sostenible":"sustainable transport","tranvía":"tram",
"trapo":"cloth","tratado":"treaty","tratamiento":"treatment",
"trece":"thirteen","tregua":"truce","treinta":"thirty","tren":"train",
"tres":"three","tribunal":"court","trigo":"wheat","tristeza":"sadness",
"trompeta":"trumpet","tronco":"trunk","tropical":"tropical",
"trueno":"thunder","tráfico":"traffic","tráiler":"trailer",
"trípode":"tripod","tsunami":"tsunami","tubería":"pipe","tulipán":"tulip",
"turbina":"turbine","turista":"tourist","turno":"turn","turrón":"nougat",
"té":"tea","técnico":"technician","tía":"aunt","tímido":"shy","tío":"uncle",
"título":"degree","tú":"you","túnel":"tunnel",
# ── U ──
"ubicación":"location","un momento":"one moment","uniforme":"uniform",
"universidad":"university","universo":"universe","uno":"one",
"urbanización":"housing development","urna":"ballot box","usted":"you (formal)",
"ustedes":"you all","uva":"grape",
# ── V ──
"vaca":"cow","vacaciones":"vacation","vacuna":"vaccine","vacío":"empty",
"valiente":"brave","valle":"valley","valor":"value",
"valor añadido":"added value","vaqueros":"jeans","variable":"variable",
"vaso":"glass","vecindario":"neighborhood","vecino":"neighbor",
"vegetariano":"vegetarian","veinte":"twenty","veintiuno":"twenty-one",
"vejez":"old age","vela":"sailboat","velocidad":"speed",
"vendedor":"seller","vender":"to sell","venir":"to come",
"ventaja competitiva":"competitive advantage","ventana":"window",
"ventanilla":"ticket window","ventilador":"fan","ventisca":"blizzard",
"ver":"to see","ver la televisión":"to watch television",
"verano":"summer","verde":"green","verdura":"vegetable",
"vergüenza":"shame","verificación":"verification","vestido":"dress",
"vestirse":"to get dressed","vestuario":"wardrobe","veterinario":"vet",
"viajar":"to travel","victoria":"victory","vida":"life",
"vida nocturna":"nightlife","videojuego":"video game",
"videollamada":"video call","viejo":"old","viento":"wind",
"viernes":"Friday","vinagre":"vinegar","vino":"wine","violencia":"violence",
"violín":"violin","viral":"viral","virus":"virus","visa":"visa",
"vista":"vision","vitamina":"vitamin","vivienda":"housing",
"vivienda social":"social housing","vivir":"to live","vodka":"vodka",
"volante":"steering wheel","volar":"to fly","volcán":"volcano",
"voleibol":"volleyball","voltaje":"voltage","voluntad":"will",
"voluntariado":"volunteering","votar":"to vote","voto":"vote",
"voz artificial":"artificial voice","vuelo":"flight","vía":"track",
"víctima":"victim","whisky":"whiskey",
# ── W/Y/Z ──
"wifi":"WiFi","y":"and","yema":"egg yolk","yo":"I","yoga":"yoga",
"yogur":"yogurt","zanahoria":"carrot","zapatillas":"sneakers",
"zapatos":"shoes","zona":"zone","zona infantil":"playground",
"zona verde":"green area","zorro":"fox",
# ── Phrases / questions ──
"¡ayuda!":"Help!","¡buen provecho!":"Enjoy your meal!",
"¡claro!":"Of course!","¡qué bonito!":"How beautiful!",
"¡qué rico!":"How delicious!","¡vamos!":"Let's go!",
"¿adónde?":"Where to?","¿cierto?":"Right?","¿cuál?":"Which?",
"¿cuándo?":"When?","¿cuánto cuesta?":"How much does it cost?",
"¿cuánto?":"How much?","¿cuántos?":"How many?",
"¿cómo estás?":"How are you?","¿cómo?":"How?",
"¿de dónde?":"Where from?","¿de quién?":"Whose?",
"¿dónde está el baño?":"Where is the bathroom?","¿dónde?":"Where?",
"¿me puede ayudar?":"Can you help me?","¿para qué?":"What for?",
"¿por qué?":"Why?","¿quién?":"Who?","¿qué hora es?":"What time is it?",
"¿qué?":"What?","¿verdad?":"Right?",
# ── Accented single words ──
"ácido":"acid","águila":"eagle","álbum":"album",
"álbum de fotos":"photo album","álgebra":"algebra","árbol":"tree",
"área de picnic":"picnic area","ático":"attic","átomo":"atom",
"él":"he","época":"era","ética profesional":"professional ethics",
"óleo":"oil painting","ópera":"opera","órbita":"orbit","órgano":"organ",
"último":"last","Dios":"God",
}

import sys

def inject(path):
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    changed = 0
    for stage in data.get("stages", []):
        for word in stage.get("words", []):
            es = word.get("es","")
            if "en" not in word:
                word["en"] = EN.get(es, "")
                changed += 1
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"{path}: +{changed} en fields")

files = sorted(glob.glob("/home/user/rainyspako/world*.json"))
for p in files:
    inject(p)
print("Done.")
